/* tslint:disable */
 
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations
  }
  collections: {
    users: User
    media: Media
    pages: Page
    posts: Post
  }
  globals: {
    'site-settings': SiteSettings
    navigation: Navigation
  }
  locale: null
  user: User & {
    collection: 'users'
  }
}

export interface UserAuthOperations {
  forgotPassword: {
    email: string
    password: string
  }
  login: {
    email: string
    password: string
  }
  registerFirstUser: {
    email: string
    password: string
  }
  unlock: {
    email: string
    password: string
  }
}

export interface User {
  id: string
  name: string
  role: 'admin' | 'editor'
  updatedAt: string
  createdAt: string
  email: string
  resetPasswordToken?: string | null
  resetPasswordExpiration?: string | null
  salt?: string | null
  hash?: string | null
  loginAttempts?: number | null
  lockUntil?: string | null
  password?: string | null
}

export interface Media {
  id: string
  alt: string
  updatedAt: string
  createdAt: string
  url?: string | null
  thumbnailURL?: string | null
  filename?: string | null
  mimeType?: string | null
  filesize?: number | null
  width?: number | null
  height?: number | null
  focalX?: number | null
  focalY?: number | null
  sizes?: {
    thumbnail?: {
      url?: string | null
      width?: number | null
      height?: number | null
      mimeType?: string | null
      filesize?: number | null
      filename?: string | null
    }
    card?: {
      url?: string | null
      width?: number | null
      height?: number | null
      mimeType?: string | null
      filesize?: number | null
      filename?: string | null
    }
    tablet?: {
      url?: string | null
      width?: number | null
      height?: number | null
      mimeType?: string | null
      filesize?: number | null
      filename?: string | null
    }
  }
}

export interface Page {
  id: string
  title: string
  slug: string
  layout?: (HeroBlock | ContentBlock | CtaBlock)[] | null
  status: 'draft' | 'published'
  publishedAt?: string | null
  meta?: {
    title?: string | null
    description?: string | null
    image?: (string | null) | Media
  }
  updatedAt: string
  createdAt: string
}

export interface HeroBlock {
  heading: string
  subheading?: string | null
  image?: (string | null) | Media
  cta?: {
    label?: string | null
    link?: string | null
  } | null
  id?: string | null
  blockName?: string | null
  blockType: 'hero'
}

export interface ContentBlock {
  content: {
    root: {
      type: string
      children: {
        type: string
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  }
  id?: string | null
  blockName?: string | null
  blockType: 'content'
}

export interface CtaBlock {
  heading: string
  description?: string | null
  buttonLabel: string
  buttonLink: string
  id?: string | null
  blockName?: string | null
  blockType: 'cta'
}

export interface Post {
  id: string
  title: string
  slug: string
  excerpt?: string | null
  content: {
    root: {
      type: string
      children: {
        type: string
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  }
  featuredImage?: (string | null) | Media
  category?: string | null
  author?: (string | null) | User
  status: 'draft' | 'published'
  publishedAt?: string | null
  meta?: {
    title?: string | null
    description?: string | null
    image?: (string | null) | Media
  }
  updatedAt: string
  createdAt: string
}

export interface SiteSettings {
  id: string
  siteName: string
  siteDescription?: string | null
  logo?: (string | null) | Media
  ogImage?: (string | null) | Media
  footerText?: string | null
  updatedAt?: string | null
  createdAt?: string | null
}

export interface Navigation {
  id: string
  header?: {
    label: string
    link: string
    children?: {
      label: string
      link: string
      id?: string | null
    }[]
    id?: string | null
  }[]
  footer?: {
    label: string
    link: string
    id?: string | null
  }[]
  updatedAt?: string | null
  createdAt?: string | null
}
